<h1>Connexion</h1> 
<form method="POST" enctype="multipart/form-data" action="<?php echo WEB_ROOT?>/user/login" class="form-horizontal">

    <div class="form-group">
        <label for="pseudo">Pseudo :</label>
        <input type="text" class="form-control" id="pseudo" name="pseudo" value="<?php if($this->errPseudo != null) echo $this->errPseudo; ?>">
    </div>
    <div class="form-group">
        <label for="pass">Mot de passe :</label>
        <input type="text" class="form-control" id="pass" name="pass">
    </div>
    
    <button type="submit" id="" class="btn btn-primary">Se connecter</button>
</form>